# Mandatory settings

name: Jesse Onolememen
paginate: 25
paginate_path: "/posts/page/:num/"
url: # add site url http://example.com/
blog_theme: light # Or use dark

# Optional settings

discus_identifier: # Add your Disqus identifier
ga_analytics: # Add your GA Tracking Id
rss_enabled: true # Change to false if not
social:
  dribbble: # Add your Dribbble handle
  facebook: # Add your Facebook handle
  flickr: # Add your Flickr handle
  github: jesster2k10
  linkedin: jesse-o-914a85122?trk=nav_responsive_tab_profile_pic
  twitter: jonolememen
  email: jesster2k10@gmail.com
  bitcoin: 1LFTEev8Mheg4pnDMdtMdcveKqTJvDeWYW

# Important settings (change at own risk)

assets:
  compress:
    css: true
    js: true
  features:
    automatic_img_size: false
  sources:
    - _assets/bower
    - _assets/fonts
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _vendor/
collections:
  my_tags:
    output: true
    permalink: /tag/:slug/
defaults:
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: articles_by_tag
exclude:
  - .bowerrc
  - .travis.yml
  - bin/*
  - bower.json
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/
gems:
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
permalink: posts/:slug
